In [1188]:
import os,sys
sys.path.insert(1, os.path.join(os.getcwd()  , '..'))

In [1189]:
import importlib, shallowsim as sb
import pandas as pd
import math

In [1190]:
importlib.reload(sb)

In [1191]:
args = sb.ModelArgs.load_from_csv("modelArgs.csv","qwen1.5-MoE") # tinyllama-1.1B qwen1.5-MoE
c = sb.Config()

In [1192]:
print(args.is_moe)
print(args.attention)

True
gqa

In [1193]:
gpu_blackwell = sb.get_gpu_info('./device/gpu_info.csv',print_console=True )

| gpu_type   |   sm |   comm_sm |   fp16 |   fp8 |   fp4 |   mem |   mem_bw |   nvlink_bw |   pcie_bw |   gpu_per_node |
|:-----------|-----:|----------:|-------:|------:|------:|------:|---------:|------------:|----------:|---------------:|
| A800       |  108 |        13 |    311 |   311 |     0 |    80 |     2039 |         600 |        50 |              8 |

In [1194]:
detail,summary = sb.prefill_time(args,gpu_blackwell, c, c.seq_len, c.kv_cache_rate, tp=8, dp=1)

In [1195]:
detail

GPU            Layers      A800
MLP_TPN           0.0  0.063319
Attn_TPN         24.0  0.054991
Shared Expert    24.0  0.014284
Combine          24.0  0.067647
Routed Expert    24.0  0.073796
Dispatch         24.0  0.054412

In [1196]:
summary

GPU             A800
Compute     3.433718
Comm        2.929412
Overlapped  0.585882
Sum         5.777248

In [1197]:
detail,summary = sb.prefill_time_pp(args, c, gpu_blackwell, c.kv_cache_rate, tp=1, dp=1, pp=1, num_chunks = 2)

In [1198]:
summary
# serial total: Sum * bs

GPU              A800
Compute     22.284163
Comm         6.635294
Overlapped   1.327059
Sum         27.592398

In [1199]:
# prefill moe

In [1200]:
tp = 2
_, ttft_sum = sb.prefill_time(args, gpu_blackwell, c, c.seq_len, c.kv_cache_rate, tp=tp, dp=2, print_console=False)
print(ttft_sum.apply(lambda x: c.seq_len/tp * (1000/ x)).loc['Sum'].to_markdown(floatfmt=".1f"))

| GPU   |     Sum |
|:------|--------:|
| A800  | 37514.9 |

# Test decode (TP & PP)

In [1201]:
args = sb.ModelArgs.load_from_csv("modelArgs.csv","qwen1.5-MoE") # qwen1.5-MoE tinyllama-1.1B
c = sb.Config()

In [1202]:
print(args.is_moe)
print(args.attention)

True
gqa

In [1203]:
gpu_blackwell_decode = sb.get_gpu_info('./device/gpu_info.csv', decoding_mode=True, print_console=True)

| gpu_type   |   sm |   comm_sm |   fp16 |   fp8 |   fp4 |   mem |   mem_bw |   nvlink_bw |   pcie_bw |   gpu_per_node |
|:-----------|-----:|----------:|-------:|------:|------:|------:|---------:|------------:|----------:|---------------:|
| A800       |  108 |        13 |    311 |   311 |     0 |    80 |     2039 |         600 |        50 |              8 |

In [1204]:

detail = sb.decode_time(
        args,                     
        gpu_blackwell_decode, 
        c,               
        [1,8,16],           
        c.seq_len,
        c.decode_len,
        gemm_group_per_device=math.ceil(args.n_routed_experts / 8),  
        device_num=8,             
        fp8_combine=False,
        tps_limit=0,
        print_console=True)

|                   |   Attn_TPN |   MLP_TPN |   SharedExpert |   RoutedExpert |   Dispatch |   Combine |   Overlapped |   TPOT |   Comm_Time_Ratio |     TPS |    Total |
|:------------------|-----------:|----------:|---------------:|---------------:|-----------:|----------:|-------------:|-------:|------------------:|--------:|---------:|
| ('A800', '1', 1)  |      0.053 |     0.019 |          0.011 |          0.081 |      0.010 |     0.010 |        0.247 |  3.756 |             0.066 | 266.230 |  266.230 |
| ('A800', '1', 2)  |      0.041 |     0.025 |          0.011 |          0.081 |      0.010 |     0.010 |        0.247 |  3.482 |             0.071 | 287.206 |  287.206 |
| ('A800', '1', 4)  |      0.028 |     0.020 |          0.011 |          0.081 |      0.010 |     0.010 |        0.247 |  3.165 |             0.078 | 316.000 |  316.000 |
| ('A800', '1', 8)  |      0.022 |     0.017 |          0.011 |          0.081 |      0.010 |     0.010 |        0.247 |  3.006 |             0.082 | 332.676 |  332.676 |
| ('A800', '8', 1)  |      0.054 |     0.021 |          0.020 |          0.118 |      0.011 |     0.013 |        0.293 |  5.114 |             0.057 | 195.534 | 1564.274 |
| ('A800', '8', 2)  |      0.042 |     0.026 |          0.020 |          0.118 |      0.011 |     0.013 |        0.293 |  4.830 |             0.061 | 207.051 | 1656.410 |
| ('A800', '8', 4)  |      0.029 |     0.020 |          0.020 |          0.118 |      0.011 |     0.013 |        0.293 |  4.507 |             0.065 | 221.889 | 1775.115 |
| ('A800', '8', 8)  |      0.022 |     0.018 |          0.020 |          0.118 |      0.011 |     0.013 |        0.293 |  4.345 |             0.067 | 230.136 | 1841.085 |
| ('A800', '16', 1) |      0.055 |     0.023 |          0.030 |          0.160 |      0.013 |     0.016 |        0.346 |  6.666 |             0.052 | 150.010 | 2400.153 |
| ('A800', '16', 2) |      0.043 |     0.027 |          0.030 |          0.160 |      0.013 |     0.016 |        0.346 |  6.370 |             0.054 | 156.981 | 2511.702 |
| ('A800', '16', 4) |      0.029 |     0.021 |          0.030 |          0.160 |      0.013 |     0.016 |        0.346 |  6.041 |             0.057 | 165.544 | 2648.707 |
| ('A800', '16', 8) |      0.022 |     0.018 |          0.030 |          0.160 |      0.013 |     0.016 |        0.346 |  5.876 |             0.059 | 170.186 | 2722.972 |

In [1086]:
result = sb.decode_time_pp(
        args,
        c,                                          
        gpu_blackwell_decode,            
        gemm_group_per_device=math.ceil(args.n_routed_experts / 8),  
        device_num=8,   
        pp=2,micro_bs_num=2,
        tps_limit=0,                                           
        fp8_combine=False,
        print_console=True)

[Decode · Pipeline-parallel with PP = 2]
|                 |    A800 |    A800 |    A800 |    A800 |     A800 |     A800 |     A800 |     A800 |     A800 |     A800 |     A800 |     A800 |
|:----------------|--------:|--------:|--------:|--------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|
| BatchSize       |   1.000 |   1.000 |   1.000 |   1.000 |    8.000 |    8.000 |    8.000 |    8.000 |   16.000 |   16.000 |   16.000 |   16.000 |
| TP              |   1.000 |   2.000 |   4.000 |   8.000 |    1.000 |    2.000 |    4.000 |    8.000 |    1.000 |    2.000 |    4.000 |    8.000 |
| LoadKV          |   0.001 |   0.001 |   0.001 |   0.001 |    0.009 |    0.009 |    0.009 |    0.009 |    0.018 |    0.018 |    0.018 |    0.018 |
| Attn_TP1        |   0.053 |   0.053 |   0.053 |   0.053 |    0.054 |    0.054 |    0.054 |    0.054 |    0.055 |    0.055 |    0.055 |    0.055 |
| Attn_TPN        |   0.053 |   0.041 |   0.028 |   0.022 |    0.054 |    0.042 |    0.029 |    0.022 |    0.055 |    0.043 |    0.029 |    0.022 |
| MLP_TPN         |   0.019 |   0.025 |   0.020 |   0.017 |    0.021 |    0.026 |    0.020 |    0.018 |    0.023 |    0.027 |    0.021 |    0.018 |
| SharedExpert    |   0.011 |   0.011 |   0.011 |   0.011 |    0.020 |    0.020 |    0.020 |    0.020 |    0.030 |    0.030 |    0.030 |    0.030 |
| RoutedExpert    |   0.081 |   0.081 |   0.081 |   0.081 |    0.118 |    0.118 |    0.118 |    0.118 |    0.160 |    0.160 |    0.160 |    0.160 |
| Dispatch        |   0.010 |   0.010 |   0.010 |   0.010 |    0.011 |    0.011 |    0.011 |    0.011 |    0.013 |    0.013 |    0.013 |    0.013 |
| Combine         |   0.010 |   0.010 |   0.010 |   0.010 |    0.013 |    0.013 |    0.013 |    0.013 |    0.016 |    0.016 |    0.016 |    0.016 |
| TPOT            |   3.756 |   3.482 |   3.165 |   3.006 |    5.114 |    4.830 |    4.507 |    4.345 |    6.666 |    6.370 |    6.041 |    5.876 |
| TPS             | 266.230 | 287.206 | 316.000 | 332.676 |  195.534 |  207.051 |  221.889 |  230.136 |  150.010 |  156.981 |  165.544 |  170.186 |
| Total           | 266.230 | 287.206 | 316.000 | 332.676 | 1564.274 | 1656.410 | 1775.115 | 1841.085 | 2400.153 | 2511.702 | 2648.707 | 2722.972 |
| ComputeTime     |   3.510 |   3.235 |   2.918 |   2.759 |    4.821 |    4.537 |    4.214 |    4.052 |    6.320 |    6.024 |    5.695 |    5.530 |
| CommTime        |   0.493 |   0.493 |   0.493 |   0.493 |    0.586 |    0.586 |    0.586 |    0.586 |    0.692 |    0.692 |    0.692 |    0.692 |
| Overlapped      |   0.247 |   0.247 |   0.247 |   0.247 |    0.293 |    0.293 |    0.293 |    0.293 |    0.346 |    0.346 |    0.346 |    0.346 |
| Comm_Time_Ratio |   0.066 |   0.071 |   0.078 |   0.082 |    0.057 |    0.061 |    0.065 |    0.067 |    0.052 |    0.054 |    0.057 |    0.059 |
| PP              |   2.000 |   2.000 |   2.000 |   2.000 |    2.000 |    2.000 |    2.000 |    2.000 |    2.000 |    2.000 |    2.000 |    2.000 |
| Bubble          |   1.878 |   1.741 |   1.582 |   1.503 |   10.228 |    9.659 |    9.013 |    8.691 |   26.665 |   25.481 |   24.163 |   23.504 |
| TPOT_PP         |   3.756 |   3.482 |   3.165 |   3.006 |    3.836 |    3.622 |    3.380 |    3.259 |    5.000 |    4.778 |    4.531 |    4.407 |
| Speedup         |   1.000 |   1.000 |   1.000 |   1.000 |    1.333 |    1.333 |    1.333 |    1.333 |    1.333 |    1.333 |    1.333 |    1.333 |

In [1087]:
dfs_o = detail.groupby(['GPU','BatchSize'],as_index=False).apply(lambda t: t[t.Total==t.Total.max()]).sort_values(['Total'],ascending=False).reset_index(drop=True)

dfs_o.style.bar(subset=['TPS','Total'],color='#6495ED')\
      .applymap(sb.gpu_category_color,props=sb.gpu_category_idx(gpu_blackwell_decode),subset=['GPU'])\
      .format(precision=3)

In [1088]:
sb.df_filter(detail,'DGX-B300',0).style\
      .bar(subset=['TPS','Total'],color='#6495ED')\
      .applymap(sb.color_positive_red, subset=['Delta'])\
      .background_gradient(subset=['Comm_Impact'],cmap=sb.cm)\
      .format(precision=3)

KeyError: "None of [Index(['Delta'], dtype='object')] are in the [columns]"