In [224]:
import os,sys
sys.path.insert(1, os.path.join(os.getcwd()  , '..'))

In [225]:
import importlib, shallowsim as sb
import pandas as pd
import math

In [226]:
importlib.reload(sb)

In [227]:
args = sb.ModelArgs.load_from_csv("modelArgs.csv","qwen3")
c = sb.Config()

In [228]:
print(args.is_moe)
print(args.attention)

True
gqa

In [229]:
gpu_blackwell = sb.get_gpu_info('./device/gpu_info.csv',print_console=True )

| gpu_type      |   sm |   comm_sm |   fp16 |   fp8 |   fp4 |   mem |   mem_bw |   nvlink_bw |   pcie_bw |   gpu_per_node |
|:--------------|-----:|----------:|-------:|------:|------:|------:|---------:|------------:|----------:|---------------:|
| DGX-B300      |  160 |        20 |   3375 |  7500 | 15000 |   288 |     8000 |         900 |       100 |              8 |
| DGX-B200      |  160 |        20 |   2250 |  4500 |  9000 |   180 |     8000 |         900 |       100 |              8 |
| GB200-NVL72   |  160 |        20 |   2500 |  5000 | 10000 |   192 |     8000 |         900 |       100 |             72 |
| GB300-NVL72   |  160 |        20 |   3750 |  7500 | 15000 |   288 |     8000 |         900 |       100 |             72 |
| Rubin-NVL144  |  110 |        12 |   6400 | 12800 | 25600 |   144 |     6500 |         900 |       100 |            144 |
| RubinU-NVL576 |  110 |        12 |   6500 | 13000 | 26000 |   256 |     8000 |        1350 |       100 |            576 |
| H200          |  132 |        20 |    989 |  1979 |     0 |   141 |     4800 |         450 |        50 |              8 |
| H800          |  132 |        20 |    989 |  1979 |     0 |    80 |     4000 |         200 |        50 |              8 |
| H20           |   78 |        10 |    148 |   296 |     0 |    96 |     4000 |         450 |        50 |              8 |
| H20-3E        |   78 |        10 |    148 |   296 |     0 |   141 |     4800 |         450 |        50 |              8 |
| MI300X        |  304 |        30 |   1307 |  2614 |     0 |   192 |     5300 |         448 |        50 |              8 |
| MI308X        |  304 |        30 |    190 |   380 |     0 |   192 |     5300 |         448 |        50 |              8 |

In [230]:
seq_len = 4383
kv_cache_rate = 0.563
decode_len = 1210
bs_list =[ 16, 32, 64, 128, 256, 512]
eplist = [ 8 , 16, 36, 72, 144, 320]

In [231]:
detail,summary = sb.prefill_time(args,gpu_blackwell,seq_len, kv_cache_rate, tp=4, dp=8)

In [232]:
detail

GPU,Layers,DGX-B300,DGX-B200,GB200-NVL72,GB300-NVL72,Rubin-NVL144,RubinU-NVL576,H200,H800,H20,H20-3E,MI300X,MI308X
GQA,0.0,0.249747,0.376320,0.338927,0.226750,0.132058,0.129519,0.949149,0.949947,6.152317,6.151519,0.676938,4.635373
DenseMLP,0.0,0.139820,0.218916,0.199142,0.139820,0.094340,0.088403,0.962668,0.969727,6.076820,6.069761,0.692905,4.578540
TP-GQA,94.0,0.172198,0.203841,0.194493,0.166448,0.142775,0.127220,0.391809,0.503911,1.692601,1.692402,0.324156,1.313765
Shared Expert,94.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Combine,94.0,0.352137,0.352137,0.138123,0.138123,0.138123,0.108749,0.654274,0.654274,0.654274,0.654274,0.654274,0.654274
Overlap1,94.0,0.179939,0.148296,-0.056370,-0.028325,-0.004652,-0.018472,0.262465,0.150363,-1.038327,-1.038128,0.330118,-0.659491
Routed Expert,94.0,0.034955,0.054729,0.049786,0.034955,0.023585,0.022101,0.240667,0.242432,1.519205,1.517440,0.173226,1.144635
Dispatch,94.0,0.125534,0.125534,0.072031,0.072031,0.072031,0.064687,0.201068,0.201068,0.201068,0.201068,0.201068,0.201068
Overlap2,94.0,0.090579,0.070805,0.022245,0.037076,0.048446,0.042587,-0.039599,-0.041363,-1.318137,-1.316372,0.027842,-0.943566

In [223]:
summary

GPU,DGX-B300,DGX-B200,GB200-NVL72,GB300-NVL72,Rubin-NVL144,RubinU-NVL576,H200,H800,H20,H20-3E,MI300X,MI308X
Compute,19.472371,24.305586,22.962173,18.931932,15.637876,14.036175,59.452782,70.156262,301.909791,301.725153,46.753949,231.089594
Comm,44.901091,44.901091,19.754485,19.754485,19.754485,16.302990,80.402183,80.402183,80.402183,80.402183,80.402183,80.402183
Sum,44.901091,44.901091,25.053223,22.417049,20.191786,18.039311,84.124454,84.290337,301.909791,301.725153,80.402183,231.089594

In [197]:
detail,summary = sb.prefill_time_pp(args, c, gpu_blackwell, kv_cache_rate, tp=4, dp=8,bs=32, pp=4, micro_bs = 1) # support tp_list /dp_list or dp in Config c

In [198]:
summary
# serial total: Sum * bs

GPU,DGX-B300,DGX-B200,GB200-NVL72,GB300-NVL72,Rubin-NVL144,RubinU-NVL576,H200,H800,H20,H20-3E,MI300X,MI308X
Compute,44.007206,61.221441,56.269710,41.414515,29.584204,27.024238,163.455698,176.097174,958.458037,957.174671,121.434578,725.355665
Comm,44.133625,44.133625,16.980641,16.980641,17.069376,13.342496,82.467251,82.467251,82.467251,82.467251,82.467251,82.467251
Sum,49.838061,62.232083,56.269710,41.414515,29.584204,27.024238,163.455698,176.097174,958.458037,957.174671,121.434578,725.355665
Bubble,78.433669,97.939015,88.555609,65.176942,46.558747,42.529949,257.241754,277.136537,1508.392976,1506.373253,191.110155,1141.543341
Total_PP,431.385181,538.664585,487.055848,358.473182,256.073111,233.914720,1414.829646,1524.250953,8296.161367,8285.052891,1051.105854,6278.488376
Serial_Total,1594.817943,1991.426648,1800.630710,1325.264493,946.694532,864.775632,5230.582328,5635.109583,30670.657173,30629.589477,3885.906490,23211.381269
Speedup,3.696970,3.696970,3.696970,3.696970,3.696970,3.696970,3.696970,3.696970,3.696970,3.696970,3.696970,3.696970

In [199]:
tp = 4
_, ttft_sum = sb.prefill_time(args, gpu_blackwell, seq_len, kv_cache_rate, tp=tp, dp=8, print_console=False)
print(ttft_sum.apply(lambda x: seq_len/tp * (1000/ x)).loc['Sum'].to_markdown(floatfmt=".1f"))

| GPU           |     Sum |
|:--------------|--------:|
| DGX-B300      | 21986.2 |
| DGX-B200      | 17607.5 |
| GB200-NVL72   | 19473.2 |
| GB300-NVL72   | 26458.1 |
| Rubin-NVL144  | 37038.3 |
| RubinU-NVL576 | 40546.9 |
| H200          |  6703.7 |
| H800          |  6222.4 |
| H20           |  1143.2 |
| H20-3E        |  1144.8 |
| MI300X        |  9023.4 |
| MI308X        |  1510.6 |

# Test decode (time & PP)

In [200]:
args = sb.ModelArgs.load_from_csv("modelArgs.csv","deepseek-v3")
c = sb.Config()

In [201]:
print(args.is_moe)
print(args.attention)

True
mla

In [202]:
gpu_blackwell_decode = sb.get_gpu_info('./device/gpu_info.csv', decoding_mode=True, print_console=True)

| gpu_type      |   sm |   comm_sm |   fp16 |   fp8 |   fp4 |   mem |   mem_bw |   nvlink_bw |   pcie_bw |   gpu_per_node |
|:--------------|-----:|----------:|-------:|------:|------:|------:|---------:|------------:|----------:|---------------:|
| DGX-B300      |  160 |        20 |   3375 |  7500 | 15000 |   288 |     8000 |         900 |       100 |              8 |
| DGX-B200      |  160 |        20 |   2250 |  4500 |  9000 |   180 |     8000 |         900 |       100 |              8 |
| GB200-NVL72   |  160 |        20 |   2500 |  5000 | 10000 |   192 |     8000 |         900 |       100 |             72 |
| GB300-NVL72   |  160 |        20 |   3750 |  7500 | 15000 |   288 |     8000 |         900 |       100 |             72 |
| Rubin-NVL144  |  110 |        12 |   6400 | 12800 | 25600 |   144 |     6500 |         900 |       100 |            144 |
| RubinU-NVL576 |  110 |        12 |   6500 | 13000 | 26000 |   256 |     8000 |        1350 |       100 |            576 |
| H200          |  132 |        20 |    989 |  1979 |     0 |   141 |     4800 |         450 |        50 |              8 |
| H800          |  132 |        20 |    989 |  1979 |     0 |    80 |     4000 |         200 |        50 |              8 |
| H20           |   78 |        10 |    148 |   296 |     0 |    96 |     4000 |         450 |        50 |              8 |
| H20-3E        |   78 |        10 |    148 |   296 |     0 |   141 |     4800 |         450 |        50 |              8 |
| MI300X        |  304 |        30 |   1307 |  2614 |     0 |   192 |     5300 |         448 |        50 |              8 |
| MI308X        |  304 |        30 |    190 |   380 |     0 |   192 |     5300 |         448 |        50 |              8 |

In [203]:

detail = sb.decode_time(
        args,                     
        gpu_blackwell_decode,                
        c.bs_list,           
        c.seq_len,
        c.decode_len,
        gemm_group_per_device=math.ceil(args.n_routed_experts / 8),  
        device_num=8,             
        fp8_combine=False,
        tps_limit=0,
        print_console=True)

|              |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B200 |   DGX-B200 |   DGX-B200 |   DGX-B200 |   DGX-B200 |   DGX-B200 |   DGX-B200 |   DGX-B200 |   DGX-B200 |   DGX-B200 |   GB200-NVL72 |   GB200-NVL72 |   GB200-NVL72 |   GB200-NVL72 |   GB200-NVL72 |   GB200-NVL72 |   GB200-NVL72 |   GB200-NVL72 |   GB200-NVL72 |   GB200-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   Rubin-NVL144 |   Rubin-NVL144 |   Rubin-NVL144 |   Rubin-NVL144 |   Rubin-NVL144 |   Rubin-NVL144 |   Rubin-NVL144 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |    H200 |    H200 |    H200 |    H200 |    H200 |    H200 |     H200 |   H20-3E |   H20-3E |   H20-3E |   H20-3E |   H20-3E |   H20-3E |   H20-3E |   MI300X |   MI300X |   MI300X |   MI300X |   MI300X |   MI300X |   MI300X |   MI300X |   MI300X |   MI300X |   MI308X |   MI308X |   MI308X |   MI308X |   MI308X |   MI308X |   MI308X |   MI308X |   MI308X |   MI308X |
|:-------------|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|--------:|--------:|--------:|--------:|--------:|--------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|
| TP           |      1.000 |      4.000 |      8.000 |      1.000 |      4.000 |      8.000 |      1.000 |      4.000 |      8.000 |      1.000 |      4.000 |      1.000 |      1.000 |      1.000 |      4.000 |      8.000 |      1.000 |      4.000 |      8.000 |      1.000 |      4.000 |      1.000 |      1.000 |         1.000 |         4.000 |         8.000 |         1.000 |         4.000 |         8.000 |         1.000 |         4.000 |         1.000 |         1.000 |         1.000 |         4.000 |         8.000 |         1.000 |         4.000 |         8.000 |         1.000 |         4.000 |         8.000 |         1.000 |         4.000 |         1.000 |         1.000 |          1.000 |          4.000 |          8.000 |          1.000 |          4.000 |          1.000 |          1.000 |           1.000 |           4.000 |           8.000 |           1.000 |           4.000 |           8.000 |           1.000 |           4.000 |           8.000 |           1.000 |           4.000 |           1.000 |           1.000 |   1.000 |   4.000 |   8.000 |   1.000 |   4.000 |   1.000 |    1.000 |    1.000 |    4.000 |    8.000 |    1.000 |    4.000 |    1.000 |    1.000 |    1.000 |    4.000 |    8.000 |    1.000 |    4.000 |    8.000 |    1.000 |    4.000 |    1.000 |    1.000 |    1.000 |    4.000 |    8.000 |    1.000 |    4.000 |    8.000 |    1.000 |    4.000 |    1.000 |    1.000 |
| BatchSize    |     16.000 |     16.000 |     16.000 |     32.000 |     32.000 |     32.000 |     64.000 |     64.000 |     64.000 |    128.000 |    128.000 |    256.000 |    512.000 |     16.000 |     16.000 |     16.000 |     32.000 |     32.000 |     32.000 |     64.000 |     64.000 |    128.000 |    256.000 |        16.000 |        16.000 |        16.000 |        32.000 |        32.000 |        32.000 |        64.000 |        64.000 |       128.000 |       256.000 |        16.000 |        16.000 |        16.000 |        32.000 |        32.000 |        32.000 |        64.000 |        64.000 |        64.000 |       128.000 |       128.000 |       256.000 |       512.000 |         16.000 |         16.000 |         16.000 |         32.000 |         32.000 |         64.000 |        128.000 |          16.000 |          16.000 |          16.000 |          32.000 |          32.000 |          32.000 |          64.000 |          64.000 |          64.000 |         128.000 |         128.000 |         256.000 |         512.000 |  16.000 |  16.000 |  16.000 |  32.000 |  32.000 |  64.000 |  128.000 |   16.000 |   16.000 |   16.000 |   32.000 |   32.000 |   64.000 |  128.000 |   16.000 |   16.000 |   16.000 |   32.000 |   32.000 |   32.000 |   64.000 |   64.000 |  128.000 |  256.000 |   16.000 |   16.000 |   16.000 |   32.000 |   32.000 |   32.000 |   64.000 |   64.000 |  128.000 |  256.000 |
| DenseMLA     |      0.017 |      0.017 |      0.017 |      0.035 |      0.035 |      0.035 |      0.070 |      0.070 |      0.070 |      0.139 |      0.139 |      0.279 |      0.557 |      0.023 |      0.023 |      0.023 |      0.047 |      0.047 |      0.047 |      0.093 |      0.093 |      0.187 |      0.374 |         0.022 |         0.022 |         0.022 |         0.043 |         0.043 |         0.043 |         0.086 |         0.086 |         0.173 |         0.345 |         0.016 |         0.016 |         0.016 |         0.032 |         0.032 |         0.032 |         0.065 |         0.065 |         0.065 |         0.130 |         0.130 |         0.260 |         0.520 |          0.013 |          0.013 |          0.013 |          0.026 |          0.026 |          0.052 |          0.105 |           0.012 |           0.012 |           0.012 |           0.023 |           0.023 |           0.023 |           0.047 |           0.047 |           0.047 |           0.094 |           0.094 |           0.187 |           0.375 |   0.095 |   0.095 |   0.095 |   0.145 |   0.145 |   0.247 |    0.450 |    0.331 |    0.331 |    0.331 |    0.618 |    0.618 |    1.192 |    2.341 |    0.079 |    0.079 |    0.079 |    0.119 |    0.119 |    0.119 |    0.199 |    0.199 |    0.358 |    0.677 |    0.264 |    0.264 |    0.264 |    0.489 |    0.489 |    0.489 |    0.939 |    0.939 |    1.838 |    3.637 |
| DenseMLP     |      0.057 |      0.057 |      0.057 |      0.058 |      0.058 |      0.058 |      0.060 |      0.060 |      0.060 |      0.064 |      0.064 |      0.072 |      0.087 |      0.057 |      0.057 |      0.057 |      0.059 |      0.059 |      0.059 |      0.062 |      0.062 |      0.069 |      0.082 |         0.057 |         0.057 |         0.057 |         0.059 |         0.059 |         0.059 |         0.062 |         0.062 |         0.068 |         0.079 |         0.057 |         0.057 |         0.057 |         0.058 |         0.058 |         0.058 |         0.060 |         0.060 |         0.060 |         0.064 |         0.064 |         0.072 |         0.087 |          0.069 |          0.069 |          0.069 |          0.070 |          0.070 |          0.071 |          0.073 |           0.056 |           0.056 |           0.056 |           0.057 |           0.057 |           0.057 |           0.058 |           0.058 |           0.058 |           0.060 |           0.060 |           0.065 |           0.074 |   0.100 |   0.100 |   0.100 |   0.108 |   0.108 |   0.123 |    0.153 |    0.143 |    0.143 |    0.143 |    0.193 |    0.193 |    0.294 |    0.496 |    0.090 |    0.090 |    0.090 |    0.095 |    0.095 |    0.095 |    0.107 |    0.107 |    0.130 |    0.175 |    0.123 |    0.123 |    0.123 |    0.162 |    0.162 |    0.162 |    0.241 |    0.241 |    0.398 |    0.712 |
| SparseMLA    |      0.067 |      0.074 |      0.072 |      0.085 |      0.083 |      0.080 |      0.120 |      0.100 |      0.094 |      0.189 |      0.135 |      0.329 |      0.607 |      0.073 |      0.075 |      0.073 |      0.097 |      0.086 |      0.081 |      0.143 |      0.106 |      0.237 |      0.424 |         0.072 |         0.075 |         0.073 |         0.093 |         0.085 |         0.081 |         0.136 |         0.104 |         0.223 |         0.395 |         0.066 |         0.073 |         0.072 |         0.082 |         0.082 |         0.079 |         0.115 |         0.099 |         0.094 |         0.180 |         0.133 |         0.310 |         0.570 |          0.063 |          0.074 |          0.073 |          0.076 |          0.082 |          0.102 |          0.155 |           0.062 |           0.072 |           0.071 |           0.073 |           0.080 |           0.078 |           0.097 |           0.094 |           0.091 |           0.144 |           0.123 |           0.237 |           0.425 |   0.145 |   0.096 |   0.085 |   0.195 |   0.116 |   0.297 |    0.500 |    0.381 |    0.155 |    0.115 |    0.668 |    0.234 |    1.242 |    2.391 |    0.129 |    0.092 |    0.083 |    0.169 |    0.108 |    0.096 |    0.249 |    0.142 |    0.408 |    0.727 |    0.314 |    0.138 |    0.106 |    0.539 |    0.201 |    0.142 |    0.989 |    0.327 |    1.888 |    3.687 |
| Combine      |      0.012 |      0.012 |      0.012 |      0.015 |      0.015 |      0.015 |      0.019 |      0.019 |      0.019 |      0.028 |      0.028 |      0.047 |      0.083 |      0.012 |      0.012 |      0.012 |      0.015 |      0.015 |      0.015 |      0.019 |      0.019 |      0.028 |      0.047 |         0.012 |         0.012 |         0.012 |         0.015 |         0.015 |         0.015 |         0.019 |         0.019 |         0.028 |         0.047 |         0.012 |         0.012 |         0.012 |         0.015 |         0.015 |         0.015 |         0.019 |         0.019 |         0.019 |         0.028 |         0.028 |         0.047 |         0.083 |          0.012 |          0.012 |          0.012 |          0.015 |          0.015 |          0.019 |          0.028 |           0.012 |           0.012 |           0.012 |           0.013 |           0.013 |           0.013 |           0.016 |           0.016 |           0.016 |           0.022 |           0.022 |           0.034 |           0.059 |   0.015 |   0.015 |   0.015 |   0.019 |   0.019 |   0.028 |    0.047 |    0.015 |    0.015 |    0.015 |    0.019 |    0.019 |    0.028 |    0.047 |    0.015 |    0.015 |    0.015 |    0.019 |    0.019 |    0.019 |    0.028 |    0.028 |    0.047 |    0.084 |    0.015 |    0.015 |    0.015 |    0.019 |    0.019 |    0.019 |    0.028 |    0.028 |    0.047 |    0.084 |
| SharedExpert |      0.008 |      0.008 |      0.008 |      0.011 |      0.011 |      0.011 |      0.012 |      0.012 |      0.012 |      0.015 |      0.015 |      0.015 |      0.016 |      0.010 |      0.010 |      0.010 |      0.014 |      0.014 |      0.014 |      0.015 |      0.015 |      0.021 |      0.021 |         0.009 |         0.009 |         0.009 |         0.013 |         0.013 |         0.013 |         0.014 |         0.014 |         0.019 |         0.019 |         0.008 |         0.008 |         0.008 |         0.011 |         0.011 |         0.011 |         0.012 |         0.012 |         0.012 |         0.015 |         0.015 |         0.015 |         0.016 |          0.009 |          0.009 |          0.009 |          0.010 |          0.010 |          0.011 |          0.013 |           0.007 |           0.007 |           0.007 |           0.009 |           0.009 |           0.009 |           0.009 |           0.009 |           0.009 |           0.011 |           0.011 |           0.011 |           0.012 |   0.035 |   0.035 |   0.035 |   0.035 |   0.035 |   0.034 |    0.035 |    0.114 |    0.114 |    0.114 |    0.114 |    0.114 |    0.110 |    0.120 |    0.031 |    0.031 |    0.031 |    0.044 |    0.044 |    0.044 |    0.050 |    0.050 |    0.069 |    0.069 |    0.106 |    0.106 |    0.106 |    0.193 |    0.193 |    0.193 |    0.237 |    0.237 |    0.368 |    0.368 |
| RoutedExpert |      0.215 |      0.215 |      0.215 |      0.233 |      0.233 |      0.233 |      0.242 |      0.242 |      0.242 |      0.268 |      0.268 |      0.268 |      0.278 |      0.227 |      0.227 |      0.227 |      0.257 |      0.257 |      0.257 |      0.271 |      0.271 |      0.316 |      0.316 |         0.224 |         0.224 |         0.224 |         0.251 |         0.251 |         0.251 |         0.264 |         0.264 |         0.304 |         0.304 |         0.215 |         0.215 |         0.215 |         0.233 |         0.233 |         0.233 |         0.242 |         0.242 |         0.242 |         0.268 |         0.268 |         0.268 |         0.278 |          0.254 |          0.254 |          0.254 |          0.264 |          0.264 |          0.269 |          0.285 |           0.208 |           0.208 |           0.208 |           0.218 |           0.218 |           0.218 |           0.223 |           0.223 |           0.223 |           0.238 |           0.238 |           0.238 |           0.244 |   0.771 |   0.771 |   0.771 |   0.771 |   0.771 |   0.766 |    0.778 |    1.406 |    1.406 |    1.406 |    1.406 |    1.406 |    1.376 |    1.455 |    0.698 |    0.698 |    0.698 |    0.800 |    0.800 |    0.800 |    0.850 |    0.850 |    1.003 |    1.003 |    1.295 |    1.295 |    1.295 |    1.993 |    1.993 |    1.993 |    2.342 |    2.342 |    3.389 |    3.389 |
| Dispatch     |      0.011 |      0.011 |      0.011 |      0.012 |      0.012 |      0.012 |      0.015 |      0.015 |      0.015 |      0.019 |      0.019 |      0.028 |      0.047 |      0.011 |      0.011 |      0.011 |      0.012 |      0.012 |      0.012 |      0.015 |      0.015 |      0.019 |      0.028 |         0.011 |         0.011 |         0.011 |         0.012 |         0.012 |         0.012 |         0.015 |         0.015 |         0.019 |         0.028 |         0.011 |         0.011 |         0.011 |         0.012 |         0.012 |         0.012 |         0.015 |         0.015 |         0.015 |         0.019 |         0.019 |         0.028 |         0.047 |          0.011 |          0.011 |          0.011 |          0.012 |          0.012 |          0.015 |          0.019 |           0.011 |           0.011 |           0.011 |           0.012 |           0.012 |           0.012 |           0.013 |           0.013 |           0.013 |           0.016 |           0.016 |           0.022 |           0.034 |   0.012 |   0.012 |   0.012 |   0.015 |   0.015 |   0.019 |    0.028 |    0.012 |    0.012 |    0.012 |    0.015 |    0.015 |    0.019 |    0.028 |    0.012 |    0.012 |    0.012 |    0.015 |    0.015 |    0.015 |    0.019 |    0.019 |    0.028 |    0.047 |    0.012 |    0.012 |    0.012 |    0.015 |    0.015 |    0.015 |    0.019 |    0.019 |    0.028 |    0.047 |
| COMP_SUM     |      0.291 |      0.298 |      0.296 |      0.328 |      0.326 |      0.323 |      0.373 |      0.354 |      0.348 |      0.473 |      0.419 |      0.612 |      0.902 |      0.310 |      0.312 |      0.310 |      0.367 |      0.356 |      0.351 |      0.430 |      0.393 |      0.573 |      0.760 |         0.305 |         0.308 |         0.306 |         0.357 |         0.348 |         0.344 |         0.415 |         0.383 |         0.546 |         0.719 |         0.290 |         0.297 |         0.296 |         0.326 |         0.326 |         0.323 |         0.369 |         0.353 |         0.347 |         0.463 |         0.416 |         0.593 |         0.864 |          0.326 |          0.336 |          0.335 |          0.350 |          0.357 |          0.382 |          0.452 |           0.277 |           0.288 |           0.287 |           0.300 |           0.306 |           0.305 |           0.329 |           0.327 |           0.323 |           0.393 |           0.373 |           0.487 |           0.681 |   0.950 |   0.901 |   0.891 |   1.000 |   0.921 |   1.097 |    1.314 |    1.900 |    1.675 |    1.635 |    2.188 |    1.754 |    2.728 |    3.966 |    0.859 |    0.821 |    0.812 |    1.013 |    0.952 |    0.939 |    1.150 |    1.043 |    1.480 |    1.799 |    1.715 |    1.539 |    1.507 |    2.725 |    2.387 |    2.328 |    3.568 |    2.906 |    5.645 |    7.444 |
| COMM_SUM     |      0.023 |      0.023 |      0.023 |      0.027 |      0.027 |      0.027 |      0.034 |      0.034 |      0.034 |      0.047 |      0.047 |      0.075 |      0.130 |      0.023 |      0.023 |      0.023 |      0.027 |      0.027 |      0.027 |      0.034 |      0.034 |      0.047 |      0.075 |         0.023 |         0.023 |         0.023 |         0.027 |         0.027 |         0.027 |         0.034 |         0.034 |         0.047 |         0.075 |         0.023 |         0.023 |         0.023 |         0.027 |         0.027 |         0.027 |         0.034 |         0.034 |         0.034 |         0.047 |         0.047 |         0.075 |         0.130 |          0.023 |          0.023 |          0.023 |          0.027 |          0.027 |          0.034 |          0.047 |           0.022 |           0.022 |           0.022 |           0.025 |           0.025 |           0.025 |           0.029 |           0.029 |           0.029 |           0.038 |           0.038 |           0.057 |           0.093 |   0.027 |   0.027 |   0.027 |   0.034 |   0.034 |   0.047 |    0.075 |    0.027 |    0.027 |    0.027 |    0.034 |    0.034 |    0.047 |    0.075 |    0.027 |    0.027 |    0.027 |    0.034 |    0.034 |    0.034 |    0.048 |    0.048 |    0.075 |    0.130 |    0.027 |    0.027 |    0.027 |    0.034 |    0.034 |    0.034 |    0.048 |    0.048 |    0.075 |    0.130 |
| Delta        |     -0.052 |     -0.059 |     -0.057 |     -0.069 |     -0.066 |     -0.063 |     -0.098 |     -0.078 |     -0.072 |     -0.157 |     -0.103 |     -0.269 |     -0.494 |     -0.060 |     -0.062 |     -0.059 |     -0.083 |     -0.072 |     -0.068 |     -0.125 |     -0.088 |     -0.210 |     -0.370 |        -0.058 |        -0.061 |        -0.059 |        -0.079 |        -0.071 |        -0.067 |        -0.117 |        -0.085 |        -0.195 |        -0.340 |        -0.051 |        -0.058 |        -0.057 |        -0.066 |        -0.066 |        -0.063 |        -0.093 |        -0.077 |        -0.072 |        -0.147 |        -0.101 |        -0.250 |        -0.456 |         -0.049 |         -0.059 |         -0.058 |         -0.059 |         -0.066 |         -0.079 |         -0.120 |          -0.047 |          -0.057 |          -0.057 |          -0.058 |          -0.064 |          -0.062 |          -0.077 |          -0.074 |          -0.071 |          -0.117 |          -0.096 |          -0.192 |          -0.343 |  -0.152 |  -0.104 |  -0.093 |  -0.196 |  -0.117 |  -0.284 |   -0.461 |   -0.468 |   -0.242 |   -0.202 |   -0.748 |   -0.315 |   -1.305 |   -2.436 |   -0.134 |   -0.096 |   -0.087 |   -0.179 |   -0.119 |   -0.106 |   -0.252 |   -0.145 |   -0.402 |   -0.666 |   -0.393 |   -0.217 |   -0.185 |   -0.699 |   -0.360 |   -0.301 |   -1.178 |   -0.516 |   -2.181 |   -3.924 |

In [204]:
result = sb.decode_time_pp(
        args,
        c,                                          
        gpu_blackwell_decode,            
        gemm_group_per_device=32,  
        device_num=8,   
        pp=4,micro_bs=1,                   # pipeline parallelism          
        fp8_combine=False,
        tps_limit=0,
        print_console=True)

[Decode · Pipeline-parallel]
|              |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B300 |   DGX-B200 |   DGX-B200 |   DGX-B200 |   DGX-B200 |   DGX-B200 |   DGX-B200 |   DGX-B200 |   DGX-B200 |   DGX-B200 |   DGX-B200 |   GB200-NVL72 |   GB200-NVL72 |   GB200-NVL72 |   GB200-NVL72 |   GB200-NVL72 |   GB200-NVL72 |   GB200-NVL72 |   GB200-NVL72 |   GB200-NVL72 |   GB200-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   GB300-NVL72 |   Rubin-NVL144 |   Rubin-NVL144 |   Rubin-NVL144 |   Rubin-NVL144 |   Rubin-NVL144 |   Rubin-NVL144 |   Rubin-NVL144 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |   RubinU-NVL576 |      H200 |      H200 |      H200 |      H200 |      H200 |      H200 |      H200 |    H20-3E |    H20-3E |    H20-3E |    H20-3E |    H20-3E |    H20-3E |    H20-3E |    MI300X |    MI300X |    MI300X |    MI300X |    MI300X |    MI300X |    MI300X |    MI300X |    MI300X |    MI300X |    MI308X |    MI308X |    MI308X |    MI308X |    MI308X |    MI308X |    MI308X |    MI308X |     MI308X |     MI308X |
|:-------------|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|-----------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|-----------:|-----------:|
| TP           |      1.000 |      4.000 |      8.000 |      1.000 |      4.000 |      8.000 |      1.000 |      4.000 |      8.000 |      1.000 |      4.000 |      1.000 |      1.000 |      1.000 |      4.000 |      8.000 |      1.000 |      4.000 |      8.000 |      1.000 |      4.000 |      1.000 |      1.000 |         1.000 |         4.000 |         8.000 |         1.000 |         4.000 |         8.000 |         1.000 |         4.000 |         1.000 |         1.000 |         1.000 |         4.000 |         8.000 |         1.000 |         4.000 |         8.000 |         1.000 |         4.000 |         8.000 |         1.000 |         4.000 |         1.000 |         1.000 |          1.000 |          4.000 |          8.000 |          1.000 |          4.000 |          1.000 |          1.000 |           1.000 |           4.000 |           8.000 |           1.000 |           4.000 |           8.000 |           1.000 |           4.000 |           8.000 |           1.000 |           4.000 |           1.000 |           1.000 |     1.000 |     4.000 |     8.000 |     1.000 |     4.000 |     1.000 |     1.000 |     1.000 |     4.000 |     8.000 |     1.000 |     4.000 |     1.000 |     1.000 |     1.000 |     4.000 |     8.000 |     1.000 |     4.000 |     8.000 |     1.000 |     4.000 |     1.000 |     1.000 |     1.000 |     4.000 |     8.000 |     1.000 |     4.000 |     8.000 |     1.000 |     4.000 |      1.000 |      1.000 |
| BatchSize    |     16.000 |     16.000 |     16.000 |     32.000 |     32.000 |     32.000 |     64.000 |     64.000 |     64.000 |    128.000 |    128.000 |    256.000 |    512.000 |     16.000 |     16.000 |     16.000 |     32.000 |     32.000 |     32.000 |     64.000 |     64.000 |    128.000 |    256.000 |        16.000 |        16.000 |        16.000 |        32.000 |        32.000 |        32.000 |        64.000 |        64.000 |       128.000 |       256.000 |        16.000 |        16.000 |        16.000 |        32.000 |        32.000 |        32.000 |        64.000 |        64.000 |        64.000 |       128.000 |       128.000 |       256.000 |       512.000 |         16.000 |         16.000 |         16.000 |         32.000 |         32.000 |         64.000 |        128.000 |          16.000 |          16.000 |          16.000 |          32.000 |          32.000 |          32.000 |          64.000 |          64.000 |          64.000 |         128.000 |         128.000 |         256.000 |         512.000 |    16.000 |    16.000 |    16.000 |    32.000 |    32.000 |    64.000 |   128.000 |    16.000 |    16.000 |    16.000 |    32.000 |    32.000 |    64.000 |   128.000 |    16.000 |    16.000 |    16.000 |    32.000 |    32.000 |    32.000 |    64.000 |    64.000 |   128.000 |   256.000 |    16.000 |    16.000 |    16.000 |    32.000 |    32.000 |    32.000 |    64.000 |    64.000 |    128.000 |    256.000 |
| DenseMLA     |      0.017 |      0.017 |      0.017 |      0.035 |      0.035 |      0.035 |      0.070 |      0.070 |      0.070 |      0.139 |      0.139 |      0.279 |      0.557 |      0.023 |      0.023 |      0.023 |      0.047 |      0.047 |      0.047 |      0.093 |      0.093 |      0.187 |      0.374 |         0.022 |         0.022 |         0.022 |         0.043 |         0.043 |         0.043 |         0.086 |         0.086 |         0.173 |         0.345 |         0.016 |         0.016 |         0.016 |         0.032 |         0.032 |         0.032 |         0.065 |         0.065 |         0.065 |         0.130 |         0.130 |         0.260 |         0.520 |          0.013 |          0.013 |          0.013 |          0.026 |          0.026 |          0.052 |          0.105 |           0.012 |           0.012 |           0.012 |           0.023 |           0.023 |           0.023 |           0.047 |           0.047 |           0.047 |           0.094 |           0.094 |           0.187 |           0.375 |     0.095 |     0.095 |     0.095 |     0.145 |     0.145 |     0.247 |     0.450 |     0.331 |     0.331 |     0.331 |     0.618 |     0.618 |     1.192 |     2.341 |     0.079 |     0.079 |     0.079 |     0.119 |     0.119 |     0.119 |     0.199 |     0.199 |     0.358 |     0.677 |     0.264 |     0.264 |     0.264 |     0.489 |     0.489 |     0.489 |     0.939 |     0.939 |      1.838 |      3.637 |
| DenseMLP     |      0.057 |      0.057 |      0.057 |      0.058 |      0.058 |      0.058 |      0.060 |      0.060 |      0.060 |      0.064 |      0.064 |      0.072 |      0.087 |      0.057 |      0.057 |      0.057 |      0.059 |      0.059 |      0.059 |      0.062 |      0.062 |      0.069 |      0.082 |         0.057 |         0.057 |         0.057 |         0.059 |         0.059 |         0.059 |         0.062 |         0.062 |         0.068 |         0.079 |         0.057 |         0.057 |         0.057 |         0.058 |         0.058 |         0.058 |         0.060 |         0.060 |         0.060 |         0.064 |         0.064 |         0.072 |         0.087 |          0.069 |          0.069 |          0.069 |          0.070 |          0.070 |          0.071 |          0.073 |           0.056 |           0.056 |           0.056 |           0.057 |           0.057 |           0.057 |           0.058 |           0.058 |           0.058 |           0.060 |           0.060 |           0.065 |           0.074 |     0.100 |     0.100 |     0.100 |     0.108 |     0.108 |     0.123 |     0.153 |     0.143 |     0.143 |     0.143 |     0.193 |     0.193 |     0.294 |     0.496 |     0.090 |     0.090 |     0.090 |     0.095 |     0.095 |     0.095 |     0.107 |     0.107 |     0.130 |     0.175 |     0.123 |     0.123 |     0.123 |     0.162 |     0.162 |     0.162 |     0.241 |     0.241 |      0.398 |      0.712 |
| SparseMLA    |      0.067 |      0.074 |      0.072 |      0.085 |      0.083 |      0.080 |      0.120 |      0.100 |      0.094 |      0.189 |      0.135 |      0.329 |      0.607 |      0.073 |      0.075 |      0.073 |      0.097 |      0.086 |      0.081 |      0.143 |      0.106 |      0.237 |      0.424 |         0.072 |         0.075 |         0.073 |         0.093 |         0.085 |         0.081 |         0.136 |         0.104 |         0.223 |         0.395 |         0.066 |         0.073 |         0.072 |         0.082 |         0.082 |         0.079 |         0.115 |         0.099 |         0.094 |         0.180 |         0.133 |         0.310 |         0.570 |          0.063 |          0.074 |          0.073 |          0.076 |          0.082 |          0.102 |          0.155 |           0.062 |           0.072 |           0.071 |           0.073 |           0.080 |           0.078 |           0.097 |           0.094 |           0.091 |           0.144 |           0.123 |           0.237 |           0.425 |     0.145 |     0.096 |     0.085 |     0.195 |     0.116 |     0.297 |     0.500 |     0.381 |     0.155 |     0.115 |     0.668 |     0.234 |     1.242 |     2.391 |     0.129 |     0.092 |     0.083 |     0.169 |     0.108 |     0.096 |     0.249 |     0.142 |     0.408 |     0.727 |     0.314 |     0.138 |     0.106 |     0.539 |     0.201 |     0.142 |     0.989 |     0.327 |      1.888 |      3.687 |
| Combine      |      0.012 |      0.012 |      0.012 |      0.015 |      0.015 |      0.015 |      0.019 |      0.019 |      0.019 |      0.028 |      0.028 |      0.047 |      0.083 |      0.012 |      0.012 |      0.012 |      0.015 |      0.015 |      0.015 |      0.019 |      0.019 |      0.028 |      0.047 |         0.012 |         0.012 |         0.012 |         0.015 |         0.015 |         0.015 |         0.019 |         0.019 |         0.028 |         0.047 |         0.012 |         0.012 |         0.012 |         0.015 |         0.015 |         0.015 |         0.019 |         0.019 |         0.019 |         0.028 |         0.028 |         0.047 |         0.083 |          0.012 |          0.012 |          0.012 |          0.015 |          0.015 |          0.019 |          0.028 |           0.012 |           0.012 |           0.012 |           0.013 |           0.013 |           0.013 |           0.016 |           0.016 |           0.016 |           0.022 |           0.022 |           0.034 |           0.059 |     0.015 |     0.015 |     0.015 |     0.019 |     0.019 |     0.028 |     0.047 |     0.015 |     0.015 |     0.015 |     0.019 |     0.019 |     0.028 |     0.047 |     0.015 |     0.015 |     0.015 |     0.019 |     0.019 |     0.019 |     0.028 |     0.028 |     0.047 |     0.084 |     0.015 |     0.015 |     0.015 |     0.019 |     0.019 |     0.019 |     0.028 |     0.028 |      0.047 |      0.084 |
| SharedExpert |      0.008 |      0.008 |      0.008 |      0.011 |      0.011 |      0.011 |      0.012 |      0.012 |      0.012 |      0.015 |      0.015 |      0.015 |      0.016 |      0.010 |      0.010 |      0.010 |      0.014 |      0.014 |      0.014 |      0.015 |      0.015 |      0.021 |      0.021 |         0.009 |         0.009 |         0.009 |         0.013 |         0.013 |         0.013 |         0.014 |         0.014 |         0.019 |         0.019 |         0.008 |         0.008 |         0.008 |         0.011 |         0.011 |         0.011 |         0.012 |         0.012 |         0.012 |         0.015 |         0.015 |         0.015 |         0.016 |          0.009 |          0.009 |          0.009 |          0.010 |          0.010 |          0.011 |          0.013 |           0.007 |           0.007 |           0.007 |           0.009 |           0.009 |           0.009 |           0.009 |           0.009 |           0.009 |           0.011 |           0.011 |           0.011 |           0.012 |     0.035 |     0.035 |     0.035 |     0.035 |     0.035 |     0.034 |     0.035 |     0.114 |     0.114 |     0.114 |     0.114 |     0.114 |     0.110 |     0.120 |     0.031 |     0.031 |     0.031 |     0.044 |     0.044 |     0.044 |     0.050 |     0.050 |     0.069 |     0.069 |     0.106 |     0.106 |     0.106 |     0.193 |     0.193 |     0.193 |     0.237 |     0.237 |      0.368 |      0.368 |
| RoutedExpert |      0.215 |      0.215 |      0.215 |      0.233 |      0.233 |      0.233 |      0.242 |      0.242 |      0.242 |      0.268 |      0.268 |      0.268 |      0.278 |      0.227 |      0.227 |      0.227 |      0.257 |      0.257 |      0.257 |      0.271 |      0.271 |      0.316 |      0.316 |         0.224 |         0.224 |         0.224 |         0.251 |         0.251 |         0.251 |         0.264 |         0.264 |         0.304 |         0.304 |         0.215 |         0.215 |         0.215 |         0.233 |         0.233 |         0.233 |         0.242 |         0.242 |         0.242 |         0.268 |         0.268 |         0.268 |         0.278 |          0.254 |          0.254 |          0.254 |          0.264 |          0.264 |          0.269 |          0.285 |           0.208 |           0.208 |           0.208 |           0.218 |           0.218 |           0.218 |           0.223 |           0.223 |           0.223 |           0.238 |           0.238 |           0.238 |           0.244 |     0.771 |     0.771 |     0.771 |     0.771 |     0.771 |     0.766 |     0.778 |     1.406 |     1.406 |     1.406 |     1.406 |     1.406 |     1.376 |     1.455 |     0.698 |     0.698 |     0.698 |     0.800 |     0.800 |     0.800 |     0.850 |     0.850 |     1.003 |     1.003 |     1.295 |     1.295 |     1.295 |     1.993 |     1.993 |     1.993 |     2.342 |     2.342 |      3.389 |      3.389 |
| Dispatch     |      0.011 |      0.011 |      0.011 |      0.012 |      0.012 |      0.012 |      0.015 |      0.015 |      0.015 |      0.019 |      0.019 |      0.028 |      0.047 |      0.011 |      0.011 |      0.011 |      0.012 |      0.012 |      0.012 |      0.015 |      0.015 |      0.019 |      0.028 |         0.011 |         0.011 |         0.011 |         0.012 |         0.012 |         0.012 |         0.015 |         0.015 |         0.019 |         0.028 |         0.011 |         0.011 |         0.011 |         0.012 |         0.012 |         0.012 |         0.015 |         0.015 |         0.015 |         0.019 |         0.019 |         0.028 |         0.047 |          0.011 |          0.011 |          0.011 |          0.012 |          0.012 |          0.015 |          0.019 |           0.011 |           0.011 |           0.011 |           0.012 |           0.012 |           0.012 |           0.013 |           0.013 |           0.013 |           0.016 |           0.016 |           0.022 |           0.034 |     0.012 |     0.012 |     0.012 |     0.015 |     0.015 |     0.019 |     0.028 |     0.012 |     0.012 |     0.012 |     0.015 |     0.015 |     0.019 |     0.028 |     0.012 |     0.012 |     0.012 |     0.015 |     0.015 |     0.015 |     0.019 |     0.019 |     0.028 |     0.047 |     0.012 |     0.012 |     0.012 |     0.015 |     0.015 |     0.015 |     0.019 |     0.019 |      0.028 |      0.047 |
| COMP_SUM     |      0.291 |      0.298 |      0.296 |      0.328 |      0.326 |      0.323 |      0.373 |      0.354 |      0.348 |      0.473 |      0.419 |      0.612 |      0.902 |      0.310 |      0.312 |      0.310 |      0.367 |      0.356 |      0.351 |      0.430 |      0.393 |      0.573 |      0.760 |         0.305 |         0.308 |         0.306 |         0.357 |         0.348 |         0.344 |         0.415 |         0.383 |         0.546 |         0.719 |         0.290 |         0.297 |         0.296 |         0.326 |         0.326 |         0.323 |         0.369 |         0.353 |         0.347 |         0.463 |         0.416 |         0.593 |         0.864 |          0.326 |          0.336 |          0.335 |          0.350 |          0.357 |          0.382 |          0.452 |           0.277 |           0.288 |           0.287 |           0.300 |           0.306 |           0.305 |           0.329 |           0.327 |           0.323 |           0.393 |           0.373 |           0.487 |           0.681 |     0.950 |     0.901 |     0.891 |     1.000 |     0.921 |     1.097 |     1.314 |     1.900 |     1.675 |     1.635 |     2.188 |     1.754 |     2.728 |     3.966 |     0.859 |     0.821 |     0.812 |     1.013 |     0.952 |     0.939 |     1.150 |     1.043 |     1.480 |     1.799 |     1.715 |     1.539 |     1.507 |     2.725 |     2.387 |     2.328 |     3.568 |     2.906 |      5.645 |      7.444 |
| COMM_SUM     |      0.023 |      0.023 |      0.023 |      0.027 |      0.027 |      0.027 |      0.034 |      0.034 |      0.034 |      0.047 |      0.047 |      0.075 |      0.130 |      0.023 |      0.023 |      0.023 |      0.027 |      0.027 |      0.027 |      0.034 |      0.034 |      0.047 |      0.075 |         0.023 |         0.023 |         0.023 |         0.027 |         0.027 |         0.027 |         0.034 |         0.034 |         0.047 |         0.075 |         0.023 |         0.023 |         0.023 |         0.027 |         0.027 |         0.027 |         0.034 |         0.034 |         0.034 |         0.047 |         0.047 |         0.075 |         0.130 |          0.023 |          0.023 |          0.023 |          0.027 |          0.027 |          0.034 |          0.047 |           0.022 |           0.022 |           0.022 |           0.025 |           0.025 |           0.025 |           0.029 |           0.029 |           0.029 |           0.038 |           0.038 |           0.057 |           0.093 |     0.027 |     0.027 |     0.027 |     0.034 |     0.034 |     0.047 |     0.075 |     0.027 |     0.027 |     0.027 |     0.034 |     0.034 |     0.047 |     0.075 |     0.027 |     0.027 |     0.027 |     0.034 |     0.034 |     0.034 |     0.048 |     0.048 |     0.075 |     0.130 |     0.027 |     0.027 |     0.027 |     0.034 |     0.034 |     0.034 |     0.048 |     0.048 |      0.075 |      0.130 |

In [ ]:
dfs_o = detail.groupby(['GPU','BatchSize'],as_index=False).apply(lambda t: t[t.Total==t.Total.max()]).sort_values(['Total'],ascending=False).reset_index(drop=True)

dfs_o.style.bar(subset=['TPS','Total'],color='#6495ED')\
      .applymap(sb.gpu_category_color,props=sb.gpu_category_idx(gpu_blackwell_decode),subset=['GPU'])\
      .format(precision=3)

/tmp/ipykernel_3826198/2282476199.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  dfs_o = detail.groupby(['GPU','BatchSize'],as_index=False).apply(lambda t: t[t.Total==t.Total.max()]).sort_values(['Total'],ascending=False).reset_index(drop=True)
/tmp/ipykernel_3826198/2282476199.py:4: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  .applymap(sb.gpu_category_color,props=sb.gpu_category_idx(gpu_blackwell_decode),subset=['GPU'])\

In [ ]:
sb.df_filter(detail,'DGX-B300',0).style\
      .bar(subset=['TPS','Total'],color='#6495ED')\
      .applymap(sb.color_positive_red, subset=['Delta'])\
      .background_gradient(subset=['Comm_Impact'],cmap=sb.cm)\
      .format(precision=3)

/tmp/ipykernel_3826198/995444697.py:3: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  .applymap(sb.color_positive_red, subset=['Delta'])\

In [ ]:
args = sb.ModelArgs.load_from_csv("modelArgs.csv","qwen3")
c = sb.Config()
c.bs_list=[16,32,64,128,256,512,1024,2048]
gpu_blackwell_decode = sb.get_gpu_info('./device/gpu_info.csv', 
                                    decoding_mode=True, print_console=True)

| gpu_type      |   sm |   comm_sm |   fp16 |   fp8 |   fp4 |   mem |   mem_bw |   nvlink_bw |   pcie_bw |   gpu_per_node |
|:--------------|-----:|----------:|-------:|------:|------:|------:|---------:|------------:|----------:|---------------:|
| DGX-B300      |  160 |        20 |   3375 |  7500 | 15000 |   288 |     8000 |         900 |       100 |              8 |
| DGX-B200      |  160 |        20 |   2250 |  4500 |  9000 |   180 |     8000 |         900 |       100 |              8 |
| GB200-NVL72   |  160 |        20 |   2500 |  5000 | 10000 |   192 |     8000 |         900 |       100 |             72 |
| GB300-NVL72   |  160 |        20 |   3750 |  7500 | 15000 |   288 |     8000 |         900 |       100 |             72 |
| Rubin-NVL144  |  110 |        12 |   6400 | 12800 | 25600 |   144 |     6500 |         900 |       100 |            144 |
| RubinU-NVL576 |  110 |        12 |   6500 | 13000 | 26000 |   256 |     8000 |        1350 |       100 |            576 |
| H200          |  132 |        20 |    989 |  1979 |     0 |   141 |     4800 |         450 |        50 |              8 |
| H800          |  132 |        20 |    989 |  1979 |     0 |    80 |     4000 |         200 |        50 |              8 |
| H20           |   78 |        10 |    148 |   296 |     0 |    96 |     4000 |         450 |        50 |              8 |
| H20-3E        |   78 |        10 |    148 |   296 |     0 |   141 |     4800 |         450 |        50 |              8 |
| MI300X        |  304 |        30 |   1307 |  2614 |     0 |   192 |     5300 |         448 |        50 |              8 |
| MI308X        |  304 |        30 |    190 |   380 |     0 |   192 |     5300 |         448 |        50 |              8 |

In [ ]:
dfs = sb.decode_time_with_ep_list(args,gpu_blackwell_decode,c,print_console=False,fp8_combine=True,tps_limit=0)

In [ ]:
dfs_o = dfs.groupby(['GPU','BatchSize'],as_index=False).apply(lambda t: t[t.Total==t.Total.max()]).sort_values(['Total'],ascending=False).reset_index(drop=True)
dfs_o.style.bar(subset=['TPS','Total'],color='#6495ED')\
      .applymap(sb.gpu_category_color,props=sb.gpu_category_idx(gpu_blackwell_decode),subset=['GPU'])\
      .applymap(sb.color_positive_red, subset=['Delta'])\
      .background_gradient(subset=['Comm_Impact'],cmap=sb.cm)\
      .format(precision=3)

/tmp/ipykernel_3826198/3398479797.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  dfs_o = dfs.groupby(['GPU','BatchSize'],as_index=False).apply(lambda t: t[t.Total==t.Total.max()]).sort_values(['Total'],ascending=False).reset_index(drop=True)
/tmp/ipykernel_3826198/3398479797.py:3: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  .applymap(sb.gpu_category_color,props=sb.gpu_category_idx(gpu_blackwell_decode),subset=['GPU'])\
/tmp/ipykernel_3826198/3398479797.py:4: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  .applymap(sb.color_positive_red, subset=['Delta'])\

In [ ]:
sb.df_filter(dfs,'Rubin-NVL144',0).style\
      .bar(subset=['TPS','Total'],color='#6495ED')\
      .applymap(sb.color_positive_red, subset=['Delta'])\
      .background_gradient(subset=['Comm_Impact'],cmap=sb.cm)\
      .format(precision=3)

/tmp/ipykernel_3826198/4080135161.py:3: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  .applymap(sb.color_positive_red, subset=['Delta'])\